const Bed_Limousine_Seat_Data = {
    DOWN_STAIR: {
        "A1": { name: "A1", choose: false },
        "A2": { name: "A2", choose: false },
        "A3": { name: "A3", choose: false },
        "A4": { name: "A4", choose: false },
        "A5": { name: "A5", choose: false },
        "A6": { name: "A6", choose: false },
        "A7": { name: "A7", choose: false },
        "A8": { name: "A8", choose: false },
        "A9": { name: "A9", choose: false },
        "A10": { name: "A10", choose: false },
        "A11": { name: "A11", choose: false },
        "A12": { name: "A12", choose: false },
        "A13": { name: "A13", choose: false },
        "A14": { name: "A14", choose: false },
        "A15": { name: "A15", choose: false },
        "A16": { name: "A16", choose: false },
        "A17": { name: "A17", choose: false },
        "A18": { name: "A18", choose: false },
    },
    UP_STAIR: {
        "B1": { name: "B1", choose: false },
        "B2": { name: "B2", choose: false },
        "B3": { name: "B3", choose: false },
        "B4": { name: "B4", choose: false },
        "B5": { name: "B5", choose: false },
        "B6": { name: "B6", choose: false },
        "B7": { name: "B7", choose: false },
        "B8": { name: "B8", choose: false },
        "B9": { name: "B9", choose: false },
        "B10": { name: "B10", choose: false },
        "B11": { name: "B11", choose: false },
        "B12": { name: "B12", choose: false },
        "B13": { name: "B13", choose: false },
        "B14": { name: "B14", choose: false },
        "B15": { name: "B15", choose: false },
        "B16": { name: "B16", choose: false },
        "B17": { name: "B17", choose: false },
        "B18": { name: "B18", choose: false },
    }
}

export default Bed_Limousine_Seat_Data